apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: botengyaocowrecog
  name: botengyaocowrecog
spec:
  template:
    metadata:
      labels:
        app: botengyaocowrecog
    spec:
      containers:
      - name: botengyaocowrecog
        image: botengyao/cowrecog:1
        args: ["-p", "127.0.0.1:80:80"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
           nvidia.com/gpu: "1"
      restartPolicy: OnFailure